services:
  router01:
    image: jodis/frr:latest
    restart: unless-stopped
    container_name: router01
    privileged: true
    stdin_open: true
    ports:
      - "1122:22"
    cap_add:
      - "ALL"
    volumes:
      - ./router01/frr.conf:/etc/frr/frr.conf:rw
      - ./shared:/shared:rw
    tty: true
    networks:
      eth0:
        ipv4_address: 12.34.1.6
      eth1:
        ipv4_address: 172.168.1.114
      eth2:
        ipv4_address: 192.168.255.114

  router02:
    image: jodis/frr:latest
    restart: unless-stopped
    container_name: router02
    privileged: true
    stdin_open: true
    ports:
      - "2222:22"
    cap_add:
      - "ALL"
    volumes:
      - ./router02/frr.conf:/etc/frr/frr.conf:rw
      - ./shared:/shared:rw
    tty: true
    networks:
      eth0:
        ipv4_address: 12.34.1.9
      eth1:
        ipv4_address: 172.168.1.112
      eth2:
        ipv4_address: 192.168.255.112

  router03:
    image: jodis/frr:latest
    restart: unless-stopped
    container_name: router03
    privileged: true
    stdin_open: true
    ports:
      - "3322:22"
    cap_add:
      - "ALL"
    volumes:
      - ./router03/frr.conf:/etc/frr/frr.conf:rw
      - ./shared:/shared:rw
    tty: true
    networks:
      eth0:
        ipv4_address: 12.34.1.11
      eth1:
        ipv4_address: 172.168.1.146
      eth2:
        ipv4_address: 192.168.255.146

  router04:
    image: jodis/frr:latest
    restart: unless-stopped
    container_name: router04
    privileged: true
    stdin_open: true
    ports:
      - "4422:22"
    cap_add:
      - "ALL"
    volumes:
      - ./router04/frr.conf:/etc/frr/frr.conf:rw
      - ./shared:/shared:rw
    tty: true
    networks:
      eth0:
        ipv4_address: 12.34.1.24
      eth1:
        ipv4_address: 172.168.1.160
      eth2:
        ipv4_address: 192.168.255.160

  trex:
    image: jodis/trex:latest
    restart: unless-stopped
    container_name: trex
    privileged: true
    stdin_open: true
    user: root
    tty: true
    ports:
      - "4500-4503:4500-4503"
      - "5522:22"
      - "8090:8000"
    cap_add:
      - "ALL"
    environment:
      - PYTHONPATH=/v3.04/trex_client/interactive:/v3.04/trex_client/interactive/trex_stl_lib/:/v3.04/trex_client/external_libs:/v3.04/trex_client/stf
    volumes:
      - ./shared:/shared:rw
    command:
      [
        "./t-rex-64",
        "--stl",
        "--prom",
        "-i",
        "--cfg",
        "/etc/trex_cfg.yaml"
      ]
    networks:
      eth0:
        ipv4_address: 12.34.1.2
      eth1:
        ipv4_address: 172.168.1.2
      eth2:
        ipv4_address: 192.168.255.2

networks:
  eth0:
    driver: bridge
    ipam:
      config:
        - subnet: 12.34.1.0/26
  eth1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.1.0/24
  eth2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.255.0/24
